#!/usr/bin/env python3
# coding=utf8
import subprocess

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Process some integers.')
    # parser.add_argument('integers', metavar='N', type=int, nargs='+',
    #                     help='an integer for the accumulator')
    parser.add_argument('zip_file', type=str)
    parser.add_argument('-d', type=str)
    # parser.add_argument('--sum', dest='accumulate', action='store_const',
    #                     const=sum, default=max,
    #                     help='sum the integers (default: find the max)')

    args = parser.parse_args()
    # print(args.accumulate(args.key))
    cmd = ["7z", "x", args.zip_file]
    if args.d:
        cmd.append("-o%s" % args.d)
    with open('/dev/shm/unzip.log', 'a') as _fd:
        _fd.write(str(cmd) + "\n")

    print(subprocess.check_call(cmd))
